<StartScreen>:
    name: "start"
    FloatLayout:
        canvas:
            Rectangle:
                source: "./images/game_start.png"
                pos: self.pos
                size: self.size
        Label:
            text: "Chocobo Racing"
            font_size: "60sp"
            font_name: "./fonts/pixel_font.ttf"
            pos_hint: {"center_x": 0.5, "top": 1.35}
        Button:
            text: "Start Game"
            font_name: "./fonts/pixel_font.ttf"
            size_hint: (0.2, 0.1)
            pos_hint: {"x": 0.4, "y": 0.1}
            background_color: (0, 0, 0, 1)
            on_press: root.start_game()

<GameScreen>:
    name: "game"
    GameWidget:

<GameWidget>:
    car_speed: 200
    is_paused: False
    canvas.before:
        Color:
            rgb: 115/255, 215/255, 255/255
        Rectangle:
            pos: self.pos
            size: self.size

        Color:
            rgb: 255/255, 165/255, 0
        Ellipse:
            pos: self.width / 2 - 75, self.height * 0.7
            size: 150, 150

        Color:
            rgb: 86/255, 125/255, 70/255
        Rectangle:
            pos: self.pos
            size: self.width, self.height * 0.8

        Color:
            rgb: 0, 0, 0
        Triangle:
            points: [0, 0, self.width / 2, 0, self.width / 4 + 50, self.height * 0.8]
        Triangle:
            points: [self.width, 0, self.width / 2, 0, self.width * 3 / 4 - 50, self.height * 0.8]

        Color:
            rgb: 0, 0, 0
        Rectangle:
            pos: self.width / 2.0 - 200, root.road_pos_y
            size: 400, self.height * 0.8

        Color:
            rgb: 1, 1, 1
        Line:
            points: [self.width / 2.0, -100, self.width / 2.0, self.height * 0.8]

    Label:
        text: "Paused"
        font_size: "50sp"
        font_name: "./fonts/pixel_font.ttf"
        pos: root.width / 2, root.height / 2
        color: 1, 1, 1, 1
        opacity: 0

    ProgressBar:
        max: 400
        value: root.car_speed
        size_hint: None, None
        width: 300
        height: 20
        pos: root.width - 350, 20

    Car:
        source: "./images/car.png"
        size_hint: None, None
        size: 300, 300
        pos: 350, -50
